// Generated by uniffi-bindgen-react-native
import { Platform, NativeModules } from 'react-native';
import turboInstaller from './NativeController';

// Get the installer - on iOS use TurboModule, on Android use NativeModules bridge
const installer = Platform.OS === 'ios' 
  ? turboInstaller 
  : (turboInstaller || NativeModules.Controller);

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
console.log('🔍 Checking Controller native module...');
console.log('Platform:', Platform.OS);
console.log('Controller installer:', installer);

// Check if module is available
const controllerAvailable = installer && typeof installer.installRustCrate === 'function';
console.log('Controller available:', controllerAvailable);

export const isNativeModuleAvailable = controllerAvailable;

if (!controllerAvailable) {
  console.warn('⚠️ Controller native module not found. Run a native build (expo run:android / expo run:ios) to enable wallet connection.');
} else {
  try {
    console.log('⚙️ Installing Controller crate...');
    const controllerResult = installer.installRustCrate();
    console.log('✅ Controller crate installed, result:', controllerResult);
  } catch (e) {
    console.error('❌ Error installing Controller:', e);
  }
}

// Export generated bindings (they will only work if native module was installed)
export * from './generated/controller';

import * as controller from './generated/controller';

// Initialize the generated bindings only if native module loaded
let initialized = false;
if (controllerAvailable && !initialized) {
  try {
    controller.default.initialize();
    initialized = true;
    console.log('✅ Controller Rust crate installed successfully!');
  } catch (e) {
    console.error('❌ Error initializing Controller bindings:', e);
  }
}

export async function uniffiInitAsync() {
  // NOOP.
}

export default {
  controller,
};
