// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#include "../cpp/controller.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import <ControllerSpec/ControllerSpec.h>

@interface Controller : NSObject <NativeControllerSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Controller : NSObject <RCTBridgeModule>
#endif

@end